/* DO NOT EDIT! GENERATED AUTOMATICALLY! */
#if HAVE_WINSOCK2_H
# include <winsock2.h> /* avoid mingw pollution on DATADIR */
#endif
#define PREFIX "/home/icrad/project/bluetoothZ/3rd/gettext-0.22.4/build"
#define EXEC_PREFIX "/home/icrad/project/bluetoothZ/3rd/gettext-0.22.4/build"
#define BINDIR "/home/icrad/project/bluetoothZ/3rd/gettext-0.22.4/build/bin"
#define SBINDIR "/home/icrad/project/bluetoothZ/3rd/gettext-0.22.4/build/sbin"
#define LIBEXECDIR "/home/icrad/project/bluetoothZ/3rd/gettext-0.22.4/build/libexec"
#define DATAROOTDIR "/home/icrad/project/bluetoothZ/3rd/gettext-0.22.4/build/share"
#define DATADIR "/home/icrad/project/bluetoothZ/3rd/gettext-0.22.4/build/share"
#define SYSCONFDIR "/home/icrad/project/bluetoothZ/3rd/gettext-0.22.4/build/etc"
#define SHAREDSTATEDIR "/home/icrad/project/bluetoothZ/3rd/gettext-0.22.4/build/com"
#define LOCALSTATEDIR "/home/icrad/project/bluetoothZ/3rd/gettext-0.22.4/build/var"
#define RUNSTATEDIR "/home/icrad/project/bluetoothZ/3rd/gettext-0.22.4/build/var/run"
#define INCLUDEDIR "/home/icrad/project/bluetoothZ/3rd/gettext-0.22.4/build/include"
#define OLDINCLUDEDIR "/usr/include"
#define DOCDIR "/home/icrad/project/bluetoothZ/3rd/gettext-0.22.4/build/share/doc/gettext"
#define INFODIR "/home/icrad/project/bluetoothZ/3rd/gettext-0.22.4/build/share/info"
#define HTMLDIR "/home/icrad/project/bluetoothZ/3rd/gettext-0.22.4/build/share/doc/gettext"
#define DVIDIR "/home/icrad/project/bluetoothZ/3rd/gettext-0.22.4/build/share/doc/gettext"
#define PDFDIR "/home/icrad/project/bluetoothZ/3rd/gettext-0.22.4/build/share/doc/gettext"
#define PSDIR "/home/icrad/project/bluetoothZ/3rd/gettext-0.22.4/build/share/doc/gettext"
#define LIBDIR "/home/icrad/project/bluetoothZ/3rd/gettext-0.22.4/build/lib"
#define LISPDIR "/home/icrad/project/bluetoothZ/3rd/gettext-0.22.4/build/share/emacs/site-lisp"
#define LOCALEDIR "/home/icrad/project/bluetoothZ/3rd/gettext-0.22.4/build/share/locale"
#define MANDIR "/home/icrad/project/bluetoothZ/3rd/gettext-0.22.4/build/share/man"
#define PKGDATADIR "/home/icrad/project/bluetoothZ/3rd/gettext-0.22.4/build/share/gettext"
#define PKGINCLUDEDIR "/home/icrad/project/bluetoothZ/3rd/gettext-0.22.4/build/include/gettext-tools"
#define PKGLIBDIR "/home/icrad/project/bluetoothZ/3rd/gettext-0.22.4/build/lib/gettext-tools"
#define PKGLIBEXECDIR "/home/icrad/project/bluetoothZ/3rd/gettext-0.22.4/build/libexec/gettext-tools"
